const state={games:[],audio:{move:null,select:null}};
const grid=document.querySelector('#game-grid'),search=document.querySelector('#search'),chapterDialog=document.querySelector('#chapters'),notice=document.querySelector('#notice');
const themeToggle=document.querySelector('#theme-toggle'),themeOptions=document.querySelector('#theme-options');
const catalogUrl=window.GAME_LIBRARY_CATALOG||'games.json';
const catalogBase=()=>new URL(catalogUrl,location.href);
const assetUrl=value=>new URL(value,catalogBase()).href;
function sound(which){const source=state.audio[which];if(!source)return;const audio=new Audio(assetUrl(source));audio.volume=.35;audio.play().catch(()=>{});}
async function loadLibrary(){try{const response=await fetch(catalogUrl);if(!response.ok)throw new Error('games.json could not be loaded');const config=await response.json();state.games=config.games||[];state.audio=config.audio||{};render();}catch(error){grid.innerHTML='<p class="empty">Could not load the game list. Check config.js and games.json.</p>';}}
function render(){const term=search.value.trim().toLowerCase();const visible=state.games.filter(game=>`${game.title} ${game.description||''} ${game.tags||''}`.toLowerCase().includes(term));grid.replaceChildren();document.querySelector('#empty').hidden=visible.length>0;for(const game of visible){const card=document.createElement('button');card.className='game-card';card.type='button';card.setAttribute('aria-label',`Open ${game.title}`);card.innerHTML=`<span class="card-art"><img class="cover" src="${escapeAttr(assetUrl(game.image))}" alt=""><span class="tag">NEW</span></span><span class="game-name">${escapeHtml(game.title)}</span>`;card.addEventListener('pointerenter',()=>sound('move'));card.addEventListener('focus',()=>sound('move'));card.addEventListener('click',()=>{sound('select');if(game.chapters)openChapters(game);else if(game.url)window.open(assetUrl(game.url),'_blank','noopener');else showNotice(`${game.title} is in your library. Add its playable URL to games.json to enable launch.`)});grid.append(card);}}
function openChapters(game){const list=document.querySelector('#chapter-list');list.replaceChildren();for(const chapter of game.chapters){const row=document.createElement('button');row.type='button';row.className='chapter-row';row.disabled=!chapter.url;row.innerHTML=`<span>Chapter ${chapter.number}</span><span class="chapter-name">${escapeHtml(chapter.name)}</span><span class="suit" aria-hidden="true">${chapter.suit||''}</span>`;if(chapter.url)row.addEventListener('click',()=>{sound('select');window.location.href=assetUrl(chapter.url)});list.append(row)}chapterDialog.showModal()}
function showNotice(message){document.querySelector('#notice-copy').textContent=message;notice.showModal()}
function escapeHtml(value=''){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function escapeAttr(value=''){return escapeHtml(value)}
search.addEventListener('input',render);document.querySelector('#close-dialog').addEventListener('click',()=>chapterDialog.close());document.querySelector('#close-notice').addEventListener('click',()=>notice.close());chapterDialog.addEventListener('click',event=>{if(event.target===chapterDialog)chapterDialog.close()});loadLibrary();
themeToggle.addEventListener('click',()=>{const open=themeOptions.hidden;themeOptions.hidden=!open;themeToggle.setAttribute('aria-expanded',String(open));sound('move')});
themeOptions.addEventListener('click',event=>{const choice=event.target.closest('[data-theme]');if(!choice)return;document.documentElement.dataset.theme=choice.dataset.theme;localStorage.setItem('dills-games-theme',choice.dataset.theme);themeOptions.querySelectorAll('[data-theme]').forEach(item=>item.setAttribute('aria-checked',String(item===choice)));themeOptions.hidden=true;themeToggle.setAttribute('aria-expanded','false');sound('select')});
document.addEventListener('click',event=>{if(!event.target.closest('.theme-menu')){themeOptions.hidden=true;themeToggle.setAttribute('aria-expanded','false')}});
const savedTheme=localStorage.getItem('dills-games-theme');if(savedTheme&&themeOptions.querySelector(`[data-theme="${savedTheme}"]`)){document.documentElement.dataset.theme=savedTheme;themeOptions.querySelectorAll('[data-theme]').forEach(item=>item.setAttribute('aria-checked',String(item.dataset.theme===savedTheme)))}
